guthib_bb/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from memo import views as memo_views
from homepage import views as homepage_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('allauth.urls')),
    path('register/', user_views.register, name='register'),
    path('user/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('memo/', include('memo.memo_urls')),
    path('announcement/', include('memo.announcement_urls')),
]

# print(settings.STATIC_ROOT, settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = homepage_views.error_page
handler500 = homepage_views.error_page

memo/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import PostListView, PostDetailView, MemoCreateView, PostUpdateView, PostDeleteView, ArchivedPostListView
from . import views

urlpatterns = [
    path('', login_required(PostListView.as_view()), name='memo_home'),
    path('archived/', ArchivedPostListView.as_view(), name='archived-memo'),
    path('post/<int:pk>/', login_required(PostDetailView.as_view()), name='post-detail'),
    path('post/new/', MemoCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='memo_about'),
    path('create_comment/', views.create_comment, name='create_comment'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('update_comment/', views.update_comment, name='update_comment'),
]

users/urls.py
from django.urls import path
from . import views
from memo.views import UserMemosView
from .models import User

urlpatterns = [
    path('<int:pk>/profile_update/', views.profile_update, name='profile_update'),
    path('<int:pk>/profile/', views.profile, name="profile"),
    path('<int:pk>/memos/', UserMemosView.as_view(), name='user_memos'),
    path('<int:pk>/preferences/', views.preferences, name='preferences'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    # show_email = models.BooleanField(default=True)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)
    
    def get_absolute_url(self):
        # return reverse('profile_update', kwargs={'pk':self.pk})
        return reverse('profile', kwargs={'pk':self.pk})
    
class UserPreferences(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='preferences')
    show_email = models.BooleanField(default=True)
    theme_color = models.CharField(max_length=20, null=True, blank=True, default='default')
    
    def __str__(self):
        return f'{self.user.username} Preferences'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, UserPreferences


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'bio']

class PreferencesUpdateForm(forms.ModelForm):
    theme_color = forms.CharField(max_length=20, required=True, label="Theme Color")                                  
    class Meta:
        model = UserPreferences
        fields = ['show_email', 'theme_color']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, PreferencesUpdateForm
from .models import User, Profile
# from memo.views import UserMemosView
from django.core.exceptions import PermissionDenied
from allauth.socialaccount.models import SocialAccount


# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in.')
            form.save()
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile_update(request, pk):
    profile = Profile.objects.get(pk=pk)
    user = profile.user

    if not request.user.is_superuser and user != request.user:
        raise PermissionDenied

    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account has been updated!')
            return redirect('profile', pk=pk)
    else:
        u_form = UserUpdateForm(instance=user)
        p_form = ProfileUpdateForm(instance=user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'user': user
    }
    return render(request, 'users/profile_update.html', context)

def profile(request, pk):
    profile = Profile.objects.get(pk=pk)
    user = profile.user
    # memos_count = UserMemosView.get_context_data(user).get('memos_count')
    if request.user.is_superuser or user == request.user:
        update_allow = True
    else:
        update_allow = False

    context = {
        'user': user,
        'update_allow': update_allow,
        # 'memos_count': memos_count
    }
    return render(request, 'users/profile.html', context)

def preferences(request, pk):
    user = Profile.objects.get(pk=pk).user
    preferences = user.preferences
    if not request.user.is_superuser and user != request.user:
        raise PermissionDenied
    
    if request.method == 'POST':
        p_form = PreferencesUpdateForm(request.POST, instance=preferences)
        if p_form.is_valid():
            p_form.save()
            messages.success(request, f'Preferences have been updated!')
            return redirect('preferences', pk=pk)
    else:
        p_form = PreferencesUpdateForm(instance=preferences)
    
    context = {
        'p_form': p_form,
        'user': user
    }
    return render(request, 'users/preferences.html', context)


# messages.debug
# messages.info
# messages.success
# messages.warning
# messages.error

users/templates/users/login.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% load static %}
{% block content %}
    <div class="content-section no-scroll">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <small class="text-muted ml-2">
                    <a href="/accounts/password/reset/">Forgot Password?</a>
                </small>
            </div>
        </form>
        <!-- <div>
            <p>Or login with:</p>
            <a href="{% provider_login_url 'google' %}" class="btn btn-primary">Google</a>
        </div> -->

        <div class="divider">
            <span class="divider-line"></span>
            <span class="divider-text">Or</span>
            <span class="divider-line"></span>
        </div>

        <div class="google-login-container">
            <a href="{% provider_login_url 'google' %}" class="google-login-btn">
                <img src="{% static 'homepage/google_logo.svg' %}" alt="Google Logo" class="google-logo">
                <span class="btn-text">Sign in with Google</span>
            </a> 
        </div>

        <div class="border-top pt3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "homepage/base.html" %}
{% block content %}
<h2>You have been logged out</h2>
    <div class="border-top pt3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section no-scroll">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "homepage/base.html" %}
{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "homepage/base.html" %}
{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password.
    </div>
{% endblock content %}

users/templates/users/preferences.html
{% extends 'homepage/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content-section no-scroll">
    <h1>Preferences</h1>
    <p>Here you can change your preferences.</p>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Change Preferences</legend>
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Confirm</button>
            </div>
        </form>
    </div>
{% endblock %}
{% block scripts %}
<script>

     let theme_color_input = $("#id_theme_color");
     theme_color_input.addClass("d-none");

     function convertHexColorToHSL (hex_color)
     {
        let r = parseInt(hex_color.substr(1,2),16);
        let g = parseInt(hex_color.substr(3,2),16);
        let b = parseInt(hex_color.substr(5,2),16);

        r /= 255, g /= 255, b /= 255;
        
        let max = Math.max(r, g, b), min = Math.min(r, g, b);
        let h, s, l = (max + min) / 2;
        
        if(max == min){
            h = s = 0; // achromatic
        } else {
            let d = max - min;
            s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
            
            switch(max){
                case r: h = (g - b) / d + (g < b ? 6 : 0); break;
                case g: h = (b - r) / d + 2; break;
                case b: h = (r - g) / d + 4; break;
            }   
            
            h /= 6;
        }
        
        h = Math.round(h * 360);
        s = Math.round(s * 100);
        l = Math.round(l * 100);

        return [h, s, l];
     }

     function hslToHex(hsl) {
        let h = hsl[0];
        let s = hsl[1];
        let l = hsl[2];

        l /= 100;
        const a = s * Math.min(l, 1 - l) / 100;
        const f = n => {
          const k = (n + h / 30) % 12;
          const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
          return Math.round(255 * color).toString(16).padStart(2, '0');   // convert to Hex and prefix "0" if needed
        };
        return `#${f(0)}${f(8)}${f(4)}`;
      }
      

    function updateThemeColorInputFromColorPicker ()
    {
        let color_picker = $("#colorpicker");
        let color = color_picker.val();
        let primary = convertHexColorToHSL(color);
        theme_color_input.val("[" + primary + "]");
        updateColors(primary);
    }

     let combo_box_html = `
        <select class="form-control" id="id_theme_color">
            <option value="default">Default</option>
            <option value="random">Random</option>
            <option value="custom">Custom</option>
        </select>
     `;

     let color_picker_html = `
        <input type="color" id="colorpicker" class="d-none" style="width: 100%;" value="#E1FF00">
     `;

    let combo_box = $(combo_box_html);

    let color_picker = $(color_picker_html);
    color_picker.on("input", updateThemeColorInputFromColorPicker);

    function updateComboBoxFromThemeColorInput ()
    {
        let theme_color = theme_color_input.val();
        if (theme_color == "default") {
            combo_box.val("default");
        } else if (theme_color == "random") {
            combo_box.val("random");
        } else {
            combo_box.val("custom");
            color_picker.removeClass("d-none");
            color_picker.val(hslToHex(JSON.parse(theme_color)));
        }
    }

     combo_box.on("change", function() {
        if (this.value == "custom") {
            color_picker.removeClass("d-none");
            updateThemeColorInputFromColorPicker ();
        } else {
            color_picker.addClass("d-none");
            theme_color_input.val(this.value);
        }
     });

     combo_box.insertAfter(theme_color_input);
     color_picker.insertAfter(combo_box);
     updateComboBoxFromThemeColorInput ();
     
</script>
{% endblock %}

users/templates/users/profile.html
{% extends "homepage/base.html" %}
{% load custom_filters %}
{% load static %}
{% block content %}
    <div class="content-section no-scroll">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user|format_username }}</h2>
            {% if user.preferences.show_email %}
                <p class="text-secondary">{{ user.email }}</p>
            {% endif %}
            <a href="{% url 'user_memos' pk=user.pk %}">Memos posted</a>
            <!-- <p class="text-secondary">{{ user.profile.bio }}</p> -->
        </div>
        {% if request.user == user %}
            <!-- Three dot menu -->
            <div class="dropdown">
                <!-- Three dots icon -->
                <div class="dropbtn icons btn-right showLeft" onclick="showDropdown(event)">
                <div class="dot"></div>
                <div class="dot"></div>
                <div class="dot"></div>
                </div>
                <!-- Menu -->
                <div id="myDropdown" class="dropdown-content">
                    <a class="btn" href="/accounts/social/connections/">Link/Unlink Account</a>
                    <a class="btn" href="/accounts/password/reset/">Set/Reset Password</a>
                    <a class="btn" href="{% url 'preferences' user.profile.pk %}">Change Preferences</a>
                </div>
            </div>
        {% endif %}
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            <h2>Bio</h2>
            <p class="article-content">{{ user.profile.bio }}</p>
        </fieldset>
        {% if update_allow == True %}
            <div>
                <a class="btn btn-outline-info btn-sm mt-1 mb-1" href="{% url 'profile_update' user.profile.pk %}">Update</a>
            </div>
        {% endif %}
    </form>
  </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'homepage/comments.js' %}"></script>
{% endblock scripts %}

users/templates/users/profile_update.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="content-section no-scroll">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <!-- <p class="text-secondary">{{ user.email }}</p> -->
            {% if user.profile.show_email %}
                <p class="text-secondary">{{ user.email }}</p>
            {% endif %}
            <!-- <p class="text-secondary">{{ user.profile.bio }}</p> -->
        </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Confirm</button>
        </div>
    </form>
  </div>
{% endblock content %}

users/templates/users/register.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% load static %}
{% block content %}
    <div class="content-section no-scroll">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>

        <div class="divider">
            <span class="divider-line"></span>
            <span class="divider-text">Or</span>
            <span class="divider-line"></span>
        </div>

        <div class="google-login-container">
            <a href="{% provider_login_url 'google' %}" class="google-login-btn">
                <img src="{% static 'homepage/google_logo.svg' %}" alt="Google Logo" class="google-logo">
                <span class="btn-text">Sign in with Google</span>
            </a> 
        </div>

        <div class="border-top pt3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}